function love.conf(t)
    t.identity = nil                    -- セーブ・ディレクトリの名称 (string)
    t.appendidentity = false            -- このフラグはソースディレクトリの後にセーブディレクトリのファイルを検索するどうか (boolean)
    t.version = "11.3"                  -- このゲームの作成に使用した LÖVE のバージョン (string)
    t.console = false                   -- コンソールの表示 (boolean, Windows 専用)
    t.accelerometerjoystick = true      -- iOS と Andorid で加速度センサーをジョイスティックと見せかけることを有効にするか (boolean)
    t.externalstorage = false           -- true にすると Android で外部ストレージにファイルの保存 (およびセーブ・ディレクトリからの読み込み) を行います (boolean)
    t.gammacorrect = false              -- 対応システムでの動作時、ガンマ補正レンダリングを有効にするか (boolean)
 
    t.audio.mic = false                 -- Android で録音機能 (マイク) のアクセスと使用許可を得るかどうか (boolean)
    t.audio.mixwithsystem = true        -- LÖVE の起動中に他のアプリのバックグラウンド音楽を再生を続けるか (boolean, iOS と Android のみ)
 
    t.window.title = "Ghost Scooping"         -- ウィンドウのタイトル (string)
    t.window.icon = "/assets/img/kawauso.png"                 -- ウィンドウのアイコンとして使用する画像のファイルパス (string)
    t.window.width = 1280                -- ウィンドウの幅 (number)
    t.window.height = 960               -- ウィンドウの高さ (number)
    t.window.borderless = false         -- ウィンドウの境界線を非表示 (boolean)
    t.window.resizable = false          -- 利用者がウィンドウの大きさを変更できるかどうか (boolean)
    t.window.minwidth = 1               -- ウィンドウの大きさが変更可能な場合におけるウィンドウの最小の幅 (number)
    t.window.minheight = 1              -- ウィンドウの大きさが変更可能な場合におけるウィンドウの最小の高さ (number)
    t.window.fullscreen = false         -- 全画面表示の有効化 (boolean)
    t.window.fullscreentype = "desktop" -- 排他的な全画面表示 ("exclusive") またはデスクトップ ("desktop") による全画面表示方式の中から選択 (string)
    t.window.usedpiscale = true         -- DPI の自動スケーリングの有効化 (boolean)
    t.window.vsync = 1                  -- 垂直同期の有効化 (boolean)
    t.window.msaa = 0                   -- 多重サンプリングされたアンチエイリアシングにて使用するサンプル数 (number)
    t.window.depth = nil                -- 深度バッファにおけるビット当たりのサンプル数です
    t.window.stencil = nil              -- ステンシルバッファにおけるビット当たりのサンプル数です
    t.window.display = 1                -- ウィンドウの表示先となるモニタの番号 (number)
    t.window.highdpi = false            -- Retina ディスプレイ上のウィンドウで high-dpi モードを有効にするか (boolean)
    t.window.x = nil                    -- 指定先のディスプレイにあるウィンドウ位置の x 座標 (number)
    t.window.y = nil                    -- 指定先のディスプレイにあるウィンドウ位置の y 座標 (number)

    t.modules.audio = true              -- audio モジュールの有効化 (boolean)
    t.modules.data = true               -- data モジュールの有効化 (boolean)
    t.modules.event = true              -- event モジュールの有効化 (boolean)
    t.modules.font = true               -- font モジュールの有効化 (boolean)
    t.modules.graphics = true           -- graphics モジュールの有効化 (boolean)
    t.modules.image = true              -- image モジュールの有効化 (boolean)
    t.modules.joystick = true           -- joystick モジュールの有効化 (boolean)
    t.modules.keyboard = true           -- keyboard モジュールの有効化 (boolean)
    t.modules.math = true               -- math モジュールの有効化 (boolean)
    t.modules.mouse = true              -- mouse モジュールの有効化 (boolean)
    t.modules.physics = true            -- physics モジュールの有効化 (boolean)
    t.modules.sound = true              -- sound モジュールの有効化 (boolean)
    t.modules.system = true             -- system モジュールの有効化 (boolean)
    t.modules.thread = true             -- thread モジュールの有効化 (boolean)
    t.modules.timer = true              -- timer モジュールの有効化 (boolean)、無効にすると love.update のデルタ時間は 0 になります。
    t.modules.touch = true              -- touch モジュールの有効化 (boolean)
    t.modules.video = true              -- video モジュールの有効化 (boolean)
    t.modules.window = true             -- window モジュールの有効化 (boolean)
end